name: daily-fare-SH-to-SZ

on:
  schedule:
  - cron: "0,10,20,30,40,50 * * * *"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install --only=prod
      working-directory: .
    - name: fetch
      run: node index.js
      working-directory: .
      # for github app auth
      env:
        clientSecret: ${{ secrets.clientSecret }}
        privateKey: ${{ secrets.privateKey }}
        
        
